# Task :- 5 CREDIT CARD FRAUD DETECTION

This is 5th task odf CodSoft Data Science Internship .
 
In this task ,I will be Using creditCard data  and build the model which will tell whether it fraud transaction or not.

As informed ,I  will be using  Logistic Regression and random forest  as our model

In [1]:
# importing required libraries 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

# for warning error filtering 
import warnings 
warnings.filterwarnings('ignore')

In [2]:
# display dataset 
data = pd.read_csv('creditcard.csv')

data.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

This dataset presents transactions that occurred in two days, where we have 492 frauds out of 284,807 transactions. The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.

The feature 'Amount' is the transaction Amount, this feature can be used for example-dependant cost-sensitive learning. Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise.

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [4]:
print("Dataset has "+str(len(data))+" observation ")
print ("Dataset  has "+str(len(data.columns))+" variables or payments ")

Dataset has 284807 observation
Dataset  has 31 variables or payments

In [5]:
# checking any null values 
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

The dataset does not  have any null values.
So, we will check for unique  values of traget output

In [6]:
data['Class'].unique()
data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

Here 0 refers to normal transaction 
and 1 refers to fraud transaction

As our dataset is unbalanced . So , we will create new balanced  dataset including all fraud transaction and  normal transaction

In [18]:
normal_transaction = data[data["Class"]==0]
fraud_transaction  = data[data["Class"]==1]
normal_dataset = normal_transaction.sample(n=500,random_state=50, replace = False )
fraud_dataset = fraud_transaction.sample( n=492, replace = False)

# display new normal transaction  dataset
normal_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
221207,142473.0,0.239604,0.808191,-0.572786,-0.874384,1.461577,0.030722,0.982558,-0.059670,0.016921,...,-0.396580,-0.885459,-0.035828,-0.334150,-0.414628,0.123162,0.051523,-0.159054,3.57,0
149509,91384.0,0.256508,1.066401,-0.062290,-0.381929,1.208575,-0.751310,1.259359,-0.638496,1.261901,...,0.136753,1.163617,-0.265133,-0.638847,-0.703434,-0.250834,0.328288,0.088605,1.90,0
74824,55774.0,1.494973,-0.383319,-0.668531,-1.046925,-0.035121,-0.416992,-0.186323,-0.165578,-1.274527,...,0.158633,0.352192,-0.312974,-0.792995,0.907474,-0.028748,-0.036032,-0.021448,10.00,0
91770,63621.0,-2.827215,-2.463081,1.849263,2.447249,0.387849,0.154154,-2.436528,1.165707,1.301479,...,0.153079,0.601354,-0.921800,0.139167,-1.156443,-0.248752,0.580148,-0.615341,25.90,0
216430,140474.0,1.199209,-3.231464,-0.978825,-1.264881,-2.113752,-0.075494,-0.867869,-0.065970,-1.216290,...,0.038784,-0.710346,-0.066659,-0.449216,-0.835435,-0.485197,-0.065486,0.044979,550.00,0

In [19]:
# display fraud transaction dataset
fraud_dataset

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
10568,17520.0,-5.268053,9.067613,-15.960728,10.296603,-4.708241,-3.395375,-11.161057,5.499963,-5.667376,...,2.004110,0.191058,0.622928,-1.209264,-0.374799,0.648798,1.584697,0.720056,1.00,1
221018,142394.0,-3.367770,0.099249,-6.148487,3.401955,0.458307,-1.571630,-1.358708,0.672409,-3.188001,...,0.861308,1.249301,1.850627,-0.117471,1.219815,0.000251,1.036011,0.004367,320.01,1
107067,70270.0,-1.512516,1.133139,-1.601052,2.813401,-2.664503,-0.310371,-1.520895,0.852996,-1.496495,...,0.729828,0.485286,0.567005,0.323586,0.040871,0.825814,0.414482,0.267265,318.11,1
243393,151916.0,-5.488032,3.329561,-5.996296,3.601720,-2.023926,-1.737393,-4.396859,0.228394,-1.675884,...,1.719631,0.343209,0.133584,0.833340,-0.839776,0.502010,-1.937473,1.521218,0.01,1
154697,102625.0,-4.221221,2.871121,-5.888716,6.890952,-3.404894,-1.154394,-7.739928,2.851363,-2.507569,...,1.620591,1.567947,-0.578007,-0.059045,-1.829169,-0.072429,0.136734,-0.599848,7.59,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151807,96291.0,-3.552173,5.426461,-3.731810,6.679062,-2.187543,2.433940,-8.748110,-12.108284,-2.856359,...,-5.688990,2.510980,0.953933,-0.542506,-0.620152,0.406013,0.023025,0.164741,33.59,1
154719,102671.0,-4.991758,5.213340,-9.111326,8.431986,-3.435516,-1.827565,-7.114303,3.431207,-3.875643,...,1.189423,0.247858,0.294448,-0.548504,-0.174617,0.406703,-0.402339,-0.882886,0.00,1
102782,68357.0,1.232604,-0.548931,1.087873,0.894082,-1.433055,-0.356797,-0.717492,0.003167,-0.100397,...,-0.448671,-0.517568,0.012833,0.699217,0.527258,-0.322607,0.080805,0.035427,19.59,1
9509,14152.0,-4.710529,8.636214,-15.496222,10.313349,-4.351341,-3.322689,-10.788373,5.060381,-5.689311,...,1.990545,0.223785,0.554408,-1.204042,-0.450685,0.641836,1.605958,0.721644,1.00,1
106998,70229.0,0.315642,1.636778,-1.519650,4.028571,-1.186794,-0.789813,-2.279807,0.472988,-1.657635,...,0.345921,-0.108002,-0.165442,0.279895,0.808783,0.117363,0.589595,0.309064,3.79,1

After creating the dataset of almost equal number of observation , we will  merge it and form one new dataset

In [23]:
new_data = pd.concat([normal_dataset,fraud_dataset],axis=0)
# display new dataset 
new_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
221207,142473.0,0.239604,0.808191,-0.572786,-0.874384,1.461577,0.030722,0.982558,-0.059670,0.016921,...,-0.396580,-0.885459,-0.035828,-0.334150,-0.414628,0.123162,0.051523,-0.159054,3.57,0
149509,91384.0,0.256508,1.066401,-0.062290,-0.381929,1.208575,-0.751310,1.259359,-0.638496,1.261901,...,0.136753,1.163617,-0.265133,-0.638847,-0.703434,-0.250834,0.328288,0.088605,1.90,0
74824,55774.0,1.494973,-0.383319,-0.668531,-1.046925,-0.035121,-0.416992,-0.186323,-0.165578,-1.274527,...,0.158633,0.352192,-0.312974,-0.792995,0.907474,-0.028748,-0.036032,-0.021448,10.00,0
91770,63621.0,-2.827215,-2.463081,1.849263,2.447249,0.387849,0.154154,-2.436528,1.165707,1.301479,...,0.153079,0.601354,-0.921800,0.139167,-1.156443,-0.248752,0.580148,-0.615341,25.90,0
216430,140474.0,1.199209,-3.231464,-0.978825,-1.264881,-2.113752,-0.075494,-0.867869,-0.065970,-1.216290,...,0.038784,-0.710346,-0.066659,-0.449216,-0.835435,-0.485197,-0.065486,0.044979,550.00,0

In [24]:
new_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Time,992.0,85987.701613,47260.426203,0.000000,45708.250000,77954.500000,131195.500000,172089.000000
V1,992.0,-2.433146,5.500554,-30.552380,-2.896429,-0.861074,0.982784,2.318610
V2,992.0,1.796833,3.694036,-10.779893,-0.151493,0.951025,2.845852,22.057729
V3,992.0,-3.427156,6.247609,-31.103685,-5.113334,-1.250805,0.394147,4.079168
V4,992.0,2.289455,3.190089,-4.463847,-0.153988,1.393133,4.222927,12.114672
V5,992.0,-1.576335,4.179451,-22.105532,-1.803275,-0.444643,0.444040,11.095089
V6,992.0,-0.672462,1.736209,-6.406267,-1.534454,-0.638118,0.130703,6.474115
V7,992.0,-2.798255,5.828247,-43.557242,-3.066415,-0.659734,0.275831,5.802537
V8,992.0,0.291712,4.882417,-41.044261,-0.217334,0.186194,0.876820,20.007208
V9,992.0,-1.258741,2.334763,-13.434066,-2.324444,-0.685031,0.218390,5.937526
V10,992.0,-2.788100,4.558496,-24.588262,-4.551515,-0.899157,0.014123,9.263796
V11,992.0,1.859821,2.781913,-3.139342,-0.223091,0.994524,3.564360,12.018913
V12,992.0,-3.097216,4.586236,-18.683715,-5.458138,-0.816557,0.223316,3.694409
V13,992.0,-0.078972,1.063535,-3.127795,-0.832086,-0.063125,0.666124,3.063137
V14,992.0,-3.447665,4.662296,-19.214325,-6.668877,-1.014360,0.119139,5.366087
V15,992.0,-0.067144,1.017469,-4.498945,-0.631256,-0.024514,0.632843,2.929704
V16,992.0,-2.072250,3.461026,-14.129855,-3.520662,-0.664669,0.258229,3.664296
V17,992.0,-3.288259,5.963959,-25.162799,-5.254303,-0.493075,0.283225,6.739384
V18,992.0,-1.114178,2.395405,-9.498746,-1.768802,-0.356607,0.362675,3.790316
V19,992.0,0.333624,1.278829,-3.681904,-0.422457,0.267093,0.983172,5.228342
V20,992.0,0.201347,1.075375,-6.406493,-0.182042,0.041370,0.477087,11.059004
V21,992.0,0.330907,2.807344,-22.797604,-0.182460,0.126594,0.645756,27.202839
V22,992.0,-0.009392,1.182297,-8.887017,-0.541855,-0.018499,0.555265,8.361985
V23,992.0,-0.035937,1.234164,-19.254328,-0.236810,-0.036572,0.190727,7.382624
V24,992.0,-0.066152,0.569491,-2.432631,-0.402861,0.000201,0.364259,1.212145
V25,992.0,0.019691,0.673265,-4.781606,-0.307094,0.050200,0.399692,2.208209
V26,992.0,0.028737,0.496731,-1.380052,-0.304140,-0.015690,0.359171,2.745261
V27,992.0,0.079318,1.038334,-7.263482,-0.064002,0.045272,0.465772,3.052358
V28,992.0,0.031466,0.446817,-3.310366,-0.061831,0.032336,0.212157,1.909665
Amount,992.0,106.661351,237.180908,0.000000,1.720000,20.000000,99.990000,2849.940000
Class,992.0,0.495968,0.500236,0.000000,0.000000,0.000000,1.000000,1.000000

 We head to model selection and training

In [42]:
# import required model from sklearn 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [51]:
x = new_data.drop(['Class'],axis=1)
y = new_data[['Class']]

In [52]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.2,random_state=50)

In [55]:
# Logistic Regression model 
model_1 = LogisticRegression()
model_1.fit(X_train,Y_train)
Y_predict_1 = model_1.predict(X_test)
# Evaluating model performance 
accuracy_score_1 = accuracy_score(Y_test,Y_predict_1)
precision_score_1 = precision_score(Y_test,Y_predict_1)
recall_score_1 = recall_score(Y_test,Y_predict_1)
f1_score_1 = f1_score(Y_test,Y_predict_1)

# display the model performance 
print(" Logistic Regression Accuracy: ",accuracy_score_1)
print(" Logistic Regression Precision: ",precision_score_1)
print(" Logistic Regression recall: ", recall_score_1)
print(" Logistic Regression F1-score: ",f1_score_1)

 Logistic Regression Accuracy:  0.9396984924623115
 Logistic Regression Precision:  0.96875
 Logistic Regression recall:  0.9117647058823529
 Logistic Regression F1-score:  0.9393939393939394

In [58]:
# Random forest model 
model_2 = RandomForestClassifier(n_estimators=100,random_state= 42)
model_2.fit(X_train,Y_train)
Y_pred_2 = model_2.predict(X_test)

# Evaluating  classifier model performance 
accuracy_score_2 = accuracy_score(Y_test,Y_pred_2)
precision_score_2 = precision_score(Y_test,Y_pred_2)
recall_score_2 = recall_score(Y_test,Y_pred_2)
f1_score_2 = f1_score(Y_test,Y_pred_2)

# display classifier model performance 
print(" Logistic Regression Accuracy: ",accuracy_score_2)
print(" Logistic Regression Precision: ",precision_score_2)
print(" Logistic Regression recall: ", recall_score_2)
print(" Logistic Regression F1-score: ",f1_score_2)

 Logistic Regression Accuracy:  0.9396984924623115
 Logistic Regression Precision:  0.9891304347826086
 Logistic Regression recall:  0.8921568627450981
 Logistic Regression F1-score:  0.9381443298969072

#  Thank You !